
# https://pixi.sh/latest/integration/ci/github_actions/?utm_source=chatgpt.com#multiple-environments
[workspace]
#channels = ["conda-forge", "https://conda.rosettacommons.org", "https://conda.graylab.jhu.edu"]
channels = ["conda-forge", "https://conda.rosettacommons.org"]
name = "pyrosetta-pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pyrosetta = "*"


[pypi-dependencies]
pyrosetta-distributed = "*"


[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.py314.dependencies]
python = "3.14.*"


[environments]
py310 = ["py310"]
py311 = ["py311"]
py312 = ["py312"]
py313 = ["py313"]
py314 = ["py314"]
