name: PyRosetta

on:
    push:
        branches: ['*']
        tags: ['*']
    pull_request:
        branches: ['*']
    schedule:
    # Run Every Monday 4 AM UTC
        - cron: '0 4 * * 1'

env:
  CARGO_TERM_COLOR: always

jobs:
  pixi:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          environment: [py310, py311, py312, py313, py314, ]
    steps:
    - uses: actions/checkout@v4
    - uses: prefix-dev/setup-pixi@v0.9.2
      with:
        environments: ${{ matrix.environment }}
        manifest-path: pyrosetta/pixi/pixi.toml

    - name: distributed.cluster
      run: |
        #cd pyrosetta/pixi && pixi run -e ${{ matrix.environment }} test
        # cd pyrosetta/pixi && pixi run python -m unittest pyrosetta.tests.*
        cd pyrosetta/pixi && pixi run python -m unittest discover -s pyrosetta.tests.distributed.cluster
